name: solana_wallets_flutter_example
description: Demonstrates how to use the solana_wallets_flutter plugin.

publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  solana_wallets_flutter:
    path: ../
  cupertino_icons: ^1.0.2
  solana: ^0.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
