name: solana_wallets_flutter
description: A flutter plugin to connect to a users wallet like phantom, solflare, etc.
version: 1.1.1
homepage: https://github.com/EPNW/solana_wallets_flutter

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.5
  inject_js: ^2.0.0
  flutter_svg: ^2.0.2
  meta: ^1.8.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/loader.js

false_secrets:
 - /assets/loader.js