import { Transaction, Message } from '@solana/web3.js';
import {
    AlphaWalletAdapter,
    AvanaWalletAdapter,
    BackpackWalletAdapter,
    BitKeepWalletAdapter,
    BitpieWalletAdapter,
    BloctoWalletAdapter,
    BraveWalletAdapter,
    CensoWalletAdapter,
    CloverWalletAdapter,
    Coin98WalletAdapter,
    CoinbaseWalletAdapter,
    CoinhubWalletAdapter,
    ExodusWalletAdapter,
    FractalWalletAdapter,
    GlowWalletAdapter,
    HuobiWalletAdapter,
    HyperPayWalletAdapter,
    KeystoneWalletAdapter,
    KrystalWalletAdapter,
    LedgerWalletAdapter,
    MathWalletAdapter,
    NekoWalletAdapter,
    NightlyWalletAdapter,
    NufiWalletAdapter,
    OntoWalletAdapter,
    ParticleAdapter,
    PhantomWalletAdapter,
    SafePalWalletAdapter,
    SaifuWalletAdapter,
    SalmonWalletAdapter,
    SkyWalletAdapter,
    SlopeWalletAdapter,
    SolflareWalletAdapter,
    SolletWalletAdapter,
    SolletExtensionWalletAdapter,
    SolongWalletAdapter,
    SpotWalletAdapter,
    StrikeWalletAdapter,
    TokenaryWalletAdapter,
    TokenPocketWalletAdapter,
    TorusWalletAdapter,
    TrustWalletAdapter,
    WalletConnectWalletAdapter,
    XDEFIWalletAdapter,
} from '@solana/wallet-adapter-wallets';

const _wallets = [
    new AlphaWalletAdapter(),
    new AvanaWalletAdapter(),
    new BackpackWalletAdapter(),
    new BitKeepWalletAdapter(),
    new BitpieWalletAdapter(),
    new BloctoWalletAdapter(),
    new BraveWalletAdapter(),
    new CensoWalletAdapter(),
    new CloverWalletAdapter(),
    new Coin98WalletAdapter(),
    new CoinbaseWalletAdapter(),
    new CoinhubWalletAdapter(),
    new ExodusWalletAdapter(),
    new FractalWalletAdapter(),
    new GlowWalletAdapter(),
    new HuobiWalletAdapter(),
    new HyperPayWalletAdapter(),
    new KeystoneWalletAdapter(),
    new KrystalWalletAdapter(),
    new LedgerWalletAdapter(),
    new MathWalletAdapter(),
    new NekoWalletAdapter(),
    new NightlyWalletAdapter(),
    new NufiWalletAdapter(),
    new OntoWalletAdapter(),
    new ParticleAdapter(),
    new PhantomWalletAdapter(),
    new SafePalWalletAdapter(),
    new SaifuWalletAdapter(),
    new SalmonWalletAdapter(),
    new SkyWalletAdapter(),
    new SlopeWalletAdapter(),
    new SolflareWalletAdapter(),
    new SolletWalletAdapter(),
    new SolletExtensionWalletAdapter(),
    new SolongWalletAdapter(),
    new SpotWalletAdapter(),
    new StrikeWalletAdapter(),
    new TokenaryWalletAdapter(),
    new TokenPocketWalletAdapter(),
    new TorusWalletAdapter(),
    new TrustWalletAdapter(),
    new WalletConnectWalletAdapter(),
    new XDEFIWalletAdapter(),
];

const solana_wallets_flutter = {
    'getWalletAdapters': () => _wallets,
    'transaction': {
        'from': (data) => Transaction.from(data),
        'populate': (message, signatures) => Transaction.populate(message, signatures),
    },
    'message': {
        'from': (data) => Message.from(data),
    },

};

if (window.dartInteropt == undefined) {
    window.dartInteropt = new Object();
}

window.dartInteropt.solana_wallets_flutter = solana_wallets_flutter;